# Edited wrangler.toml
# Fixing the node:sqlite issue for Cloudflare Workers

#:schema node_modules/wrangler/config-schema.json
name = "aiostreams"
main = "src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "../frontend/out", binding = "ASSETS", experimental_serve_directly = false}

[observability]
enabled = true

[build]
command = "npm run build"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.modules]
external = ["node:sqlite"]

# This part tells Wrangler to externalize (ignore bundling) node:sqlite module
# so your deploy won't break when undici internally tries to require it.

# Other optional configs (commented out) remain the same, no change.
# ...
